<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AdaptiveCyberDefense" nsURI="http://www.emftext.org/language/AdaptiveCyberDefense"
    nsPrefix="AdaptiveCyberDefense">
  <eClassifiers xsi:type="ecore:EClass" name="DomainDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state_variables" upperBound="-1"
        eType="#//StateVariable" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="statevariables"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action_descriptions" upperBound="-1"
        eType="#//ActionDescription" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="actiondescriptions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ActionVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial_atoms" lowerBound="1"
        upperBound="-1" eType="#//InitialAtom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventdescriptions" upperBound="-1"
        eType="#//EventDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        defaultValueLiteral="-0.00001"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionatom" lowerBound="1"
        eType="#//ActionAtom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextual_effects" upperBound="-1"
        eType="#//ContextualEffect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateVariable" eSuperTypes="#//Variable #//InitialVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilisticEffect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateatoms" upperBound="-1"
        eType="#//StateAtom" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true" eSuperTypes="#//InitialVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Formula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialAtom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="status"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialvariable" lowerBound="1"
        eType="#//InitialVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequirementStatus">
    <eLiterals name="inact" value="1"/>
    <eLiterals name="act" value="2"/>
    <eLiterals name="viol" value="3"/>
    <eLiterals name="sat" value="4"/>
    <eLiterals name="req" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialVariable" abstract="true">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="InitialState"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateAtom" eSuperTypes="#//InitialVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statevariable" lowerBound="1"
        eType="#//StateVariable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="tt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionAtom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionvariable" lowerBound="1"
        eType="#//ActionVariable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="tt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Formula" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Formula"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Formula"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Disjunction" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Formula"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Formula"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Negation" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        eType="#//Formula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parentheses" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        eType="#//Formula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Achieve" eSuperTypes="#//DeadlineRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Maintain" eSuperTypes="#//DeadlineRequirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="perUnitCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="True" eSuperTypes="#//Formula"/>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="tt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="control" value="1"/>
    <eLiterals name="exogenous" value="2"/>
    <eLiterals name="exploit" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="False" eSuperTypes="#//Formula"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeadlineRequirement" abstract="true"
      eSuperTypes="#//Requirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cancellation" eType="#//Formula"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activation" lowerBound="1"
        eType="#//Formula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadline" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnconditionalMaintain" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextualEffect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//Formula"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="change_sets" upperBound="-1"
        eType="#//ProbabilisticEffect" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="probabilisticeffects"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionatom" lowerBound="1"
        eType="#//ActionAtom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probabilisticcontextualeffect"
        upperBound="-1" eType="#//ProbabilisticContextualEffect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbabilisticContextualEffect" eSuperTypes="#//ContextualEffect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrence_probability"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        defaultValueLiteral="1"/>
  </eClassifiers>
</ecore:EPackage>
